name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t walunja1/reactjs-app:latest .
      - name: Publish Image to Docker Hub
        run: docker push walunja1/reactjs-app:latest

  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: aws-ec2
    environment:
      name: Development
    steps:
      - name: Pull image from docker
        run: docker pull walunja1/reactjs-app:latest
      - name: Delete old container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer walunja1/reactjs-app:latest
